export const ERRORS = {
  INVALID_ADDRESS: "INVALID_ADDRESS",
  WALLET_ALREADY_EXISTS: "WALLET_ALREADY_EXISTS",
  FREE_LIMIT_REACHED: "FREE_LIMIT_REACHED",
  FREE_PERIOD_EXPIRED: "FREE_PERIOD_EXPIRED",
  PRO_SUBSCRIPTION_EXPIRED: "PRO_SUBSCRIPTION_EXPIRED",
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
};
